name: Code Review

on: [pull_request]

jobs:

  # -- LINT -------------------------------------------------------------------
  tflint:
    name: Code Review - TFlint
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@ed3a0531877aca392eb870f440d9ae7aba83a6bd # tag=v1.4.0
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      # Run TFLint
      - name: tflint with reviewdog output on the PR
        uses: reviewdog/action-tflint@54a5e5aed57dcfbb4662ec548de876df33d6288d # v1.25.0

  # -- SECURITY ---------------------------------------------------------------
  tfsec:
    name: Code Review - TFSec
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      # Run TFSec
      - name: Run tfsec with reviewdog output on the PR
        uses: reviewdog/action-tfsec@18beef5056ad7aa9336a29ff8188aae6615fc6ab # v1.28.4
